---
- hosts: all
- name: Include dynamic variables 
  tasks:
  import_playbook: ../static-assignment/common.yml 
  include: ../dynamic-assignments/env-vars.yml
  tags:
    - always

-  hosts: webservers
- name: Webserver assignment
  import_playbook: ../static-assignment/webservers.yml

- name: Loadbalancers assignment
  hosts: lb
  import_playbook: ../static-assignment/loadbalancers.yml
  when: load_balancer_is_required 


